meta:
  engine: 4.1.0

units:
  kx: cx
  ky: cy
  px: kx + 2
  py: ky + 2
  
points:
  zones:
    main:
      key:
        padding: 1ky
        spread: 1kx
        anchor.shift: [50,-100] # Fix KiCad placement
        tags:
          u1: true
      columns:
        outer:
          rows:
            bottom.skip: true
            top.skip: true
            home:
              column_net: P20
              rotate: 90
              padding: -0.5
              bind: [0, 0.2]
              shift: [0.5, 0]
              tags:
                ua: false
                u15: true
        pinky:
          key:
            stagger: 0.1ky
          rows:
            top:
              column_net: P5
            home:
              column_net: P6
            bottom:
              column_net: P7
        ring:
          key:
            stagger: 0.6ky
          rows:
            top:
              column_net: P16
            home:
              column_net: P3
            bottom:
              column_net: P4
        middle:
          key:
            stagger: 0.25ky
          rows:
            top:
              column_net: P18
            home:
              column_net: P19
            bottom:
              column_net: P21
        index:
          key:
            stagger: -0.25ky
          rows:
            top:
              column_net: P0
            home:
              column_net: P14
            bottom:
              column_net: P15
        inner:
          key:
            stagger: -0.15ky
          rows:
            top:
              column_net: P1
            home:
              column_net: P20
            bottom:
              column_net: P10
      rows:
        bottom:
        home:
        top:
    thumb:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: main_index_bottom
        shift: [0.91kx, -1.32ky]
        rotate: -11
      rows:
        home:
      columns:
        tuck:
          key:
            bind: [4, 0]
            tags:
              u1: true
          rows:
            home:
              column_net: P8
        reach:
          key:
            spread: kx
            splay: -15
            rotate: 90
            origin: [-0.55kx, -0.5ky]
            bind: [6, 0, 0, 0]
            tags:
              u1: false
              u15: true
          rows:
            home:
              column_net: P9
outlines:
  raw:
    - what: rectangle
      where: true
      size: [kx, ky]
      bound: false
    - what: rectangle
      where: main_inner_home
      size: [1.52kx, 1.8ky]
      bound: true
      adjust:
        shift: [0.75kx, -0.47ky]
    - what: rectangle
      where: main_pinky_bottom
      size: [5kx, 3ky]
      bound: true
      adjust:
        shift: [2kx, 0]
    - what: circle
      radius: 157.5
      operation: subtract
      where:
        ref: main_pinky_bottom
        shift: [0, -(156.5 + 0.5kx)]
    - what: rectangle
      size: [1.5kx, 1ky]
      bound: true
      where: u15
  
  filleted:
    - what: outline
      name: raw
      fillet: 1

  keycap_outlines:
    - what: rectangle
      size: [1kx - 0.5, 1ky - 0.5] # Choc keycaps are 17.5 x 16.5
      bound: false   
      where: u1     

  keycap_outlines15:
    - what: rectangle
      size: [1.5kx - 0.5, 1ky - 0.5] # Choc keycaps are 17.5 x 16.5
      bound: false
      where: u15

  keycaps: [keycap_outlines, keycap_outlines15]

  preview:
    - what: outline
      name: filleted
      bound: false
      operation: stack
    - what: outline
      name: keycaps
      bound: false
      operation: stack

pcbs:
  rmh36:
    template: kicad8
    outlines:
      main:
        outline: filleted
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          from: "{{column_net}}"
          to: GND
          include_corner_marks: true
          include_keycap: true
          keycap_height: 16.5
          keycap_width: 17.5
          reversible: true
          solder: true
          hotswap: true
          choc_v2_support: false
          outer_pad_width_front: 2.0
          outer_pad_width_back: 2.0
      mcu:
        what: promicro_pretty
        where:
          ref: main_inner_home
        adjust:
          shift: [18, -2]
          rotate: 270
        # params:
        #   RAW: RAW
        #   GND: GND
        #   RST: RST
        #   VCC: VCC
        #   P21: P21
        #   P20: P20
        #   P19: P19
        #   P18: P18
        #   P15: P15
        #   P14: P14
        #   P16: P16
        #   P10: P10
        #   P1: P1
        #   P0: P0
        #   P2: P2
        #   P3: P3
        #   P4: P4
        #   P5: P5
        #   P6: P6
        #   P7: P7
        #   P8: P8
        #   P9: P9
      trrs:
        what: ceoloide/trrs_pj320a
        where:
          ref: main_inner_bottom
          shift: [27.2, -0.3ky]
        adjust:
          rotate: 270
        params:
          SL: GND
          R2: P2
          TP: VCC # Tip and Ring 1 are joined together
          reversible: true
          symmetric: true

