meta:
  engine: 4.1.0

units:
  kx: cx
  ky: cy
  px: kx + 2
  py: ky + 2
  
points:
  zones:
    main:
      anchor.shift: [150,-150] # Fix KiCad placement
      key:
        padding: 1ky
        spread: 1kx
        tags:
          u1: true
      columns:
        outer:
          key:
            col_net: P6
          rows:
            bottom.skip: true
            top.skip: true
            home:
              row_net: P4
              rotate: 270
              padding: -0.5
              bind: [0, 0.2]
              shift: [0.5, 0]
              tags:
                ua: false
                u15: true
        pinky:
          key:
            stagger: 0.1ky
            col_net: P7
          rows:
            top:
              row_net: P3
            home:
              row_net: P4
            bottom:
              row_net: P5
        ring:
          key:
            stagger: 0.6ky
            col_net: P8
          rows:
            top:
              row_net: P3
            home:
              row_net: P4
            bottom:
              row_net: P5
        middle:
          key:
            stagger: 0.25ky
            col_net: P9
          rows:
            top:
              row_net: P3
            home:
              row_net: P4
            bottom:
              row_net: P5
        index:
          key:
            stagger: -0.25ky
            col_net: P1
          rows:
            top:
              row_net: P3
            home:
              row_net: P4
            bottom:
              row_net: P5
        inner:
          key:
            stagger: -0.15ky
            col_net: P0
          rows:
            top:
              row_net: P3
            home:
              row_net: P4
            bottom:
              row_net: P5
      rows:
        bottom:
        home:
        top:
    thumb:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        ref: main_index_bottom
        shift: [0.91kx, -1.32ky]
        rotate: -11
      rows:
        home:
      columns:
        tuck:
          key:
            col_net: P1
            bind: [4, 0]
            tags:
              u1: true
          rows:
            home:
              row_net: P10
        reach:
          key:
            col_net: P0
            spread: kx
            splay: -15
            rotate: 90
            origin: [-0.55kx, -0.5ky]
            bind: [6, 0, 0, 0]
            tags:
              u1: false
              u15: true
          rows:
            home:
              row_net: P10
outlines:
  raw:
    - what: rectangle
      where: true
      size: [kx, ky]
      bound: false
    - what: rectangle
      where: main_inner_home
      size: [1.52kx, 1.8ky]
      bound: true
      adjust:
        shift: [0.75kx, -0.47ky]
    - what: rectangle
      where: main_pinky_bottom
      size: [5kx, 3ky]
      bound: true
      adjust:
        shift: [2kx, 0]
    - what: circle
      radius: 157.5
      operation: subtract
      where:
        ref: main_pinky_bottom
        shift: [0, -(156.5 + 0.5kx)]
    - what: rectangle
      size: [1.5kx, 1ky]
      bound: true
      where: u15
  
  filleted:
    - what: outline
      name: raw
      fillet: 1

  keycap_outlines:
    - what: rectangle
      size: [1kx - 0.5, 1ky - 0.5] # Choc keycaps are 17.5 x 16.5
      bound: false   
      where: u1     

  keycap_outlines15:
    - what: rectangle
      size: [1.5kx - 0.5, 1ky - 0.5] # Choc keycaps are 17.5 x 16.5
      bound: false
      where: u15

  keycaps: [keycap_outlines, keycap_outlines15]

  preview:
    - what: outline
      name: filleted
      bound: false
      operation: stack
    - what: outline
      name: keycaps
      bound: false
      operation: stack

pcbs:
  rmh36:
    template: kicad8
    outlines:
      main:
        outline: filleted
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          from: "{{col_net}}"
          to: "{{colrow}}"
          include_corner_marks: true
          include_keycap: false
          keycap_height: ky - 0.5
          keycap_width: kx - 0.5
          reversible: true
          solder: false
          hotswap: true
          choc_v2_support: false
          outer_pad_width_front: 1.9
          outer_pad_width_back: 1.9
      diode:
        what: ceoloide/diode_tht_sod123
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
          reversible: true
          include_thru_hole_smd_pads: true
          include_tht: true
        adjust:
          shift: [0, -4.2]
      mcu:
        what: ceoloide/mcu_nice_nano
        where:
          ref: main_inner_home
        params:
          reverse_mount: true
          reversible: true
          only_required_jumpers: true
        adjust:
          shift: [kx + 0.2, 0.8]
      trrs:
        what: ceoloide/trrs_pj320a
        where:
          ref: main_inner_bottom
          shift: [27.2, -0.14ky]
        adjust:
          rotate: 270
        params:
          SL: GND
          R2: P2
          TP: VCC # Tip and Ring 1 are joined together
          reversible: true
          symmetric: true
      mount_outer_home_above:
        what: ceoloide/mounting_hole_npth
        where:
          ref: main_outer_home
          shift: [0.5kx + 1.4, -5.5]
        params:
          hole_size: 3.2
          hole_drill: 3.2
      mount_outer_home_below:
        what: ceoloide/mounting_hole_npth
        where:
          ref: main_outer_home
          shift: [-0.5kx - 1.4, -5.5]
        params:
          hole_size: 3.2
          hole_drill: 3.2
      mount_reach_home_above:
        what: ceoloide/mounting_hole_npth
        where:
          ref: thumb_reach_home
          shift: [0.5kx + 1.4, -5.5]
        params:
          hole_size: 3.2
          hole_drill: 3.2
      mount_reach_home_below:
        what: ceoloide/mounting_hole_npth
        where:
          ref: thumb_reach_home
          shift: [-0.5kx - 1.4, -5.5]
        params:
          hole_size: 3.2
          hole_drill: 3.2
      mount_ring_bottom:
        what: ceoloide/mounting_hole_npth
        where:
          ref: main_ring_bottom
          shift: [-0.3kx, -15.6]
        params:
          hole_size: 3.2
          hole_drill: 3.2
      mount_ring_top:
        what: ceoloide/mounting_hole_npth
        where:
          ref: main_ring_top
          shift: [0.5kx, 0.35]
        params:
          hole_size: 3.2
          hole_drill: 3.2
      mount_index_bottom:
        what: ceoloide/mounting_hole_npth
        where:
          ref: main_index_bottom
          shift: [0.18kx, -25.5]
        params:
          hole_size: 3.2
          hole_drill: 3.2
      mount_index_top:
        what: ceoloide/mounting_hole_npth
        where:
          ref: main_index_top
          shift: [0.5kx, -2.1]
        params:
          hole_size: 3.2
          hole_drill: 3.2
